[files]
# Path to the directory where channel folders are. Expected structure: root_dir -> channel_dir -> YYYY-MM-DD.log 
#
# logs/
#   #russian/
#     2025-12-01.log
#     2025-12-02.log.gz
#     ...
#   #osu/
#     2025-12-01.log
#     ...
logs_path = "."

# Path to the directory with templates.
template_dir = "./templates"

# Path to the output directory (will be created if does not exist).
generate_to = "./irc-stats"

# Template of the output file's name -- %s is replaced with the channel folder's name.
save_as = "%s_curr_month.html"

[date]
# Which year and month to generate statistics for. Both values can be numbers, regular expressions (backslashes need to be escaped), or the word "current".
# Example:
#  year = "20(24|25)"
#  month = "\\d+"
year = "current"
month = "current"
